apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: apps/nginx-ingress
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: ingress-nginx
    server: {{ .Values.spec.destination.server }}
  project: nginx-ingress
