apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-backend-deployment
  labels:
    app: restaurant-backend
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: restaurant-backend
  strategy: {}
  template:
    metadata:
      labels:
        run: restaurant-backend
    spec:
      containers:
        - name: restaurant-backend
          image: ghcr.io/lapillaga/restaurant-back:latest
          resources: {}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: main
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
status: {}
