apiVersion: v1
kind: Service
metadata:
  name: restaurant-backend-service
  labels:
    app: restaurant-backend
spec:
  selector:
    run: restaurant-backend
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
