apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-backend-deployment
  labels:
    environment: dev
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: restaurant-backend
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: develop
